### ISSUE TITLE
Addition of Aaryan's model to the web interface

### ISSUE THREAD

**Issue by tiprock-network** [tiprock-network/MedicineDemand-TimeSeries#16]
Since we will experience high level of complexity, I would love us to just integrate the 3rd model and cancel out the use of power apps and use the python notebook.

**Comment by aaryan2134** [comment]
Hmm... I believe that will cause more problems and we will need to completely redo as the model is entirely built using Azure and not on Jupyter Notebooks
So, what we can do is that add a link to the app as discussed before for smooth and complete functioning

**Comment by tiprock-network** [comment]
I think it will be noble just to have 2 different apps for our purpose.
