### ISSUE TITLE
Creating an ML Model for Health Expense Prediction

### ISSUE THREAD

**Issue by aaryan2134** [tiprock-network/MedicineDemand-TimeSeries#4]
I am working on a ML Model using Azure Auto ML to predict medical expenses.

**Comment by aaryan2134** [comment]
https://github.com/tiprock-network/MedicineDemand-TimeSeries/pull/7

**Comment by tiprock-network** [comment]
Okay, still working on the other endpoint for the model. I will place an update as soon as possible.
